name: build test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: npm install
        run: npm install

      - name: Lint
        run: npm run format-check

      - name: npm test
        run: npm test

      - name: audit packages
        run: npm audit --audit-level=high
        if: matrix.operating-system == 'ubuntu-latest'
